POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "test",
  "name": "John Doe",
  "password": "test"
}

### Malformed request: short username
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "a",
  "name": "John Doe",
  "password": "password123"
}
